#!/bin/bash
vol=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ 2>/dev/null)
if echo "$vol" | grep -q "MUTED"; then
    echo "  mute "
else
    val=$(echo "$vol" | awk '{print int($2*100)}')
    if [ "$val" -lt 33 ]; then
        icon=""
    elif [ "$val" -lt 66 ]; then
        icon=""
    else
        icon=""
    fi
    echo " $icon ${val}% "
fi