#!/bin/bash
# Volume block
vol=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ 2>/dev/null)
if echo "$vol" | grep -q "MUTED"; then
    echo " mute "
else
    val=$(echo "$vol" | awk '{print int($2*100)}')
    echo " $val% "
fi